import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
       <Script
          src="https://secure.widget.cloud.opta.net/v3/v3.opta-widgets.js"
        />
        <Script
          id="opta-settings"
          dangerouslySetInnerHTML={{
            __html: `
              var opta_settings = {
                subscription_id: "590a1f32f94bfbee6bbd1b6202c76c7d",
                language: "it_IT",
                timezone: "Europe/Rome",
                opta_tracking: false,
              };
            `,
          }}
        />
        <link rel="stylesheet" href="https://secure.widget.cloud.opta.net/v3/css/v3.all.opta-widgets.css"/>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
